

gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    volumes: 
      - d:\DockerShare\GitlabCEData\config\:/etc/gitlab
      # 以下注释的部分加上就不能正常启动
      # - d:\DockerShare\GitlabCEData\data\backups:/var/opt/gitlab/backups
      # - d:\DockerShare\GitlabCEData\data\git-data:/var/opt/gitlab/git-data
      # - d:\DockerShare\GitlabCEData\data\registry:/var/opt/gitlab/registry
      - d:\DockerShare\GitlabCEData\logs\:/var/log/gitlab
    ports:
      - "3443:443"
      - "380:80"
      - "322:22"
    expose:
      - "443"
      - "80"
      - "22"
    
jbpm-showcase:
    container_name: jbpm-showcase
    image: jboss/jbpm-workbench-showcase
    restart: always
    ports:
      - "18080:8080"
      - "18001:8001"
    expose:
      - "18080"
      - "18001"

docker-registry-repo:
    container_name: docker-registry-repo
    image: registry
    restart: always
    privileged: true
    ports:
      - "5000:5000"
    volumes:
      - "D:/DockerShare/RegistryRepo/:/var/lib/registry"



mariadb1:
    container_name: mariadb1
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Vosung123
    ports:
      - 3306:3306
    volumes:
      - D:/DockerShare/MariaDB/conf:/etc/mysql
      - D:/DockerShare/MariaDB/data:/var/lib/mysql


# cnpm-local:
#     container_name: cnpm-local
#     image: hbrls/cnpmjs
#     restart: always
#     ports:
#       - "17001:7001"
#       - "17002:7002"
#     volumes:
#       - "d:/cnpm/config:/var/app/cnpmjs.org/config"
#       - "d:/cnpm/docs/:/var/app/cnpmjs.org/docs/"
#       - "d:/cnpm/storage:/var/www"