jbpm-showcase:
    container_name: jbpm-showcase
    image: jboss/jbpm-workbench-showcase
    restart: always
    ports:
      - "18080:8080"
      - "18001:8001"
    expose:
      - "18080"
      - "18001"

mariadb1:
    container_name: mariadb1
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Vosung123
    ports:
      - 3306:3306
    volumes:
      - /Users/jinfei/Laboratory/DockerShare/MariaDB/conf:/etc/mysql
      - /Users/jinfei/Laboratory/DockerShare/MariaDB/data:/var/lib/mysql

rabbitmq:
  image: rabbitmq:management
  restart: always
  ports:
    - "5672:5672"
    - "15672:15672"


sqlserver1:
    container_name: sqlserver1
    image: microsoft/mssql-server-linux:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Neural123*()
      - MSSQL_PID=Enterprise
    ports:
      - 1433:1433
# volumes加上了就不能启动
#    volumes:
#      - /Users/jinfei/Laboratory/DockerShare/MSSqlServer/mssql/data:/var/opt/mssql/data
