
orientdb1:
    container_name: orientdb
    image: orientdb
    privileged: true
    restart: always
    environment: 
      ORIENTDB_ROOT_PASSWORD: rootpwd
      ORIENTDB_NODE_NAME: odb1
    ports: 
      - "2424:2424"
      - "2480:2480"
    volumes:
      - /Users/jinfei/Laboratory/DockerShare/OrientDB/databases:/orientdb/databases
      - /Users/jinfei/Laboratory/DockerShare/OrientDB/backup:/orientdb/backup
      - /Users/jinfei/Laboratory/DockerShare/OrientDB/config:/orientdb/config
    command: /orientdb/bin/server.sh  -Ddistributed=true
