  mongoclient:
      container_name: mongoclient
      image: mongoclient/mongoclient
      restart: always
      ports:
        - 3000:3000
      volumes: 
        - /Users/jinfei/Laboratory/DockerShare/mongoclient/data:/data/db