version: '3.4'

services:
  nginx:
      privileged: true
      container_name: nginx
      image: nginx
      volumes:
        - /Users/jinfei/Laboratory/DockerShare/Nginx/etc/nginx:/etc/nginx
        - /Users/jinfei/Laboratory/DockerShare/Nginx/www:/www
      ports:
        - "80:80"
      environment:
        - NGINX_HOST=bgenius.cn
        - NGINX_PORT=80
      depends_on: 
        - gitlab-ce
      links: 
        - gitlab-ce:gitlab-ce

  # 已经测试-不改变docker-compose.yml,直接挂载已有本机文件夹重建容器，可恢复以前的数据，也就是备份的时候直接备份被挂载的本机文件夹即可
  gitlab-ce:
      privileged: true
      container_name: gitlab-ce
      image: gitlab/gitlab-ce:latest
      restart: always
      volumes: 
        - /Users/jinfei/Laboratory/DockerShare/gitlab-ce/log:/var/log/gitlab
        - /Users/jinfei/Laboratory/DockerShare/gitlab-ce/opt:/var/opt/gitlab
        - /Users/jinfei/Laboratory/DockerShare/gitlab-ce/etc:/etc/gitlab
      ports:
        - "3443:443"
        - "380:80"
        - "322:22"
      expose:
        - "443"
        - "80"
        - "22"