mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Vosung123
    ports:
      - 3306:3306
    volumes:
      - /Users/jinfei/Laboratory/DockerShare/MariaDB/conf:/etc/mysql
      - /Users/jinfei/Laboratory/DockerShare/MariaDB/data:/var/lib/mysql