sqlserver1:
    container_name: sqlserver1
    image: microsoft/mssql-server-linux:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Neural123*()
      - MSSQL_PID=Enterprise
    ports:
      - 1433:1433
#    volumes:
#      - /Users/jinfei/Laboratory/DockerShare/MSSqlServer/mssql/data:/var/opt/mssql/data
