mongo-express:
      container_name: mongodb
      image: mongo
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: Neural01@
      volumes: 
        - /Users/jinfei/Laboratory/DockerShare/MongoDB/data:/data/db
        - /Users/jinfei/Laboratory/DockerShare/MongoDB/config:/data/configdb